### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by mgiannopoulos24** [kiruthikpurpose/StarWarsReactJS#1]
Hey there,

I would like to contribute to your project but I'm not entirely sure what is the purpose of this website. Could you explain it to me please.

Thanks in advance

**Comment by kiruthikpurpose** [comment]
Thanks for your interest in the project! This is a simple React.js project where you click a button to randomly display Star Wars characters, along with details like their height and home planet, using an API. I’m still in the very early stages of development, and I’m completely new to React.js—just picked it up from a Skillshare course. I haven’t had much time to work on it, so it’s currently halfway done, and I’m not sure how to deploy it online yet.

I really appreciate your willingness to contribute! I’d love to know more about your experience with React and what caught your interest in this project. I’ll definitely keep you updated if I make any progress.

**Comment by mgiannopoulos24** [comment]
Thanks for the response. 

I've made about 5 pages with React so I know a few stuff about components. I haven't used API's a lot besides a simple Firestore DB for a project. 

I will try to help you on your project. I will implement a method to display images of each character or even better a 3D model that you can rotate.
